// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLNzbSnELqp5oljTZoEJW0ywmFoqEM4ZI',
    appId: '1:771824737829:web:28b76572e54f802e02e9cc',
    messagingSenderId: '771824737829',
    projectId: 'crud-firebase-project-d46c5',
    authDomain: 'crud-firebase-project-d46c5.firebaseapp.com',
    storageBucket: 'crud-firebase-project-d46c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBbYEC0PVUsEN6A_5x9zsgH4wc6sHkaM',
    appId: '1:771824737829:android:d73af5fd53b3f3f502e9cc',
    messagingSenderId: '771824737829',
    projectId: 'crud-firebase-project-d46c5',
    storageBucket: 'crud-firebase-project-d46c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPeD2xZJ-1PUg0yIpxxCICkwyj-GIgvos',
    appId: '1:771824737829:ios:e578beb3afb0b07702e9cc',
    messagingSenderId: '771824737829',
    projectId: 'crud-firebase-project-d46c5',
    storageBucket: 'crud-firebase-project-d46c5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPeD2xZJ-1PUg0yIpxxCICkwyj-GIgvos',
    appId: '1:771824737829:ios:e578beb3afb0b07702e9cc',
    messagingSenderId: '771824737829',
    projectId: 'crud-firebase-project-d46c5',
    storageBucket: 'crud-firebase-project-d46c5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLNzbSnELqp5oljTZoEJW0ywmFoqEM4ZI',
    appId: '1:771824737829:web:7bdddaeb067c74bb02e9cc',
    messagingSenderId: '771824737829',
    projectId: 'crud-firebase-project-d46c5',
    authDomain: 'crud-firebase-project-d46c5.firebaseapp.com',
    storageBucket: 'crud-firebase-project-d46c5.firebasestorage.app',
  );
}
